name: ci

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8","3.9","3.10", "3.11", "3.12"]

    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      
      - name: Set up Python
        uses: actions/setup-python@39cd14951b08e74b54015e9e001cdefcf80e669f # v5.1.1
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Install deps + package
        run: make install

      - name: Run full CI pipeline (lint + tests + coverage)
        run: make test-ci

      - name: Enforce coverage threshold (min 85%)
        run: |
          python - <<'PY'
          import sys, xml.etree.ElementTree as ET
          cov = float(ET.parse('coverage.xml').getroot().attrib['line-rate']) * 100
          thr = 84.5
          print(f"Coverage: {cov:.1f}% (min {thr}%)")
          sys.exit(0 if cov >= thr else 1)
          PY

      - name: Upload coverage HTML
        if: always()
        uses: codecov/codecov-action@v5
        with:
          name: coverage-html
          path: htmlcov
          token: ${{ secrets.CODECOV_API_TOKEN }}
