name: Publish to PyPI

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-publish:
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
      contents: read
    
    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          ref: ${{ github.ref }}
      
      - name: Set up Python
        uses: actions/setup-python@39cd14951b08e74b54015e9e001cdefcf80e669f # v5.1.1
        with:
          python-version: "3.11"
          cache: pip
      
      - name: Build wheel and sdist
        run: |
          python -m pip install --upgrade pip build twine
          python -m build
          twine check dist/*
      
      - name: Check tag version matches pyproject
        run: |
          TAG="${GITHUB_REF_NAME#v}"
          FILE_VERSION=$(python - <<'PY'
          from pathlib import Path
          import tomllib
          data = tomllib.loads(Path("pyproject.toml").read_text())
          print(data["project"]["version"])
          PY
          )
          echo "Tag: $TAG | pyproject: $FILE_VERSION"
          [ "$TAG" = "$FILE_VERSION" ]
      
      - name: Publish to PyPI via OIDC
        uses: pypa/gh-action-pypi-publish@release/v1