name: publish

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip

      - name: Build wheel and sdist
        run: |
          python -m pip install --upgrade pip build twine
          python -m build
          twine check dist/*

      - name: Check tag version matches pyproject
        run: |
          TAG="${GITHUB_REF_NAME#v}"
          FILE_VERSION=$(python - <<'PY'
          from pathlib import Path
          import tomllib
          data = tomllib.loads(Path("pyproject.toml").read_text())
          print(data["project"]["version"])
          PY
          )
          echo "Tag: $TAG | pyproject: $FILE_VERSION"
          [ "$TAG" = "$FILE_VERSION" ]
      
      # - name: Publish to PyPI via OIDC
      #   uses: pypa/gh-action-pypi-publish@release/v1

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          twine upload --non-interactive dist/*

          
