name: tests

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Install deps + package
        run: make install

      - name: Run full CI pipeline (lint + tests + coverage)
        run: make test-ci

      - name: Enforce coverage threshold (min 85%)
        run: |
          python - <<'PY'
          import sys, xml.etree.ElementTree as ET
          cov = float(ET.parse('coverage.xml').getroot().attrib['line-rate']) * 100
          thr = 85.0
          print(f"Coverage: {cov:.1f}% (min {thr}%)")
          sys.exit(0 if cov >= thr else 1)
          PY

      - name: Upload coverage HTML
        if: always()
        uses: codecov/codecov-action@v5
        with:
          name: coverage-html
          path: htmlcov
          token: ${{ secrets.CODECOV_API_TOKEN }}
